#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 14 11:56:50 CET 2022
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim BCDto7Seg_tb_behav -key {Behavioral:sim_1:Functional:BCDto7Seg_tb} -tclbatch BCDto7Seg_tb.tcl -view /home/saacman/Projects/HMS_Labs/lab2_combinatorial/mux_tb_behav.wcfg -log simulate.log"
xsim BCDto7Seg_tb_behav -key {Behavioral:sim_1:Functional:BCDto7Seg_tb} -tclbatch BCDto7Seg_tb.tcl -view /home/saacman/Projects/HMS_Labs/lab2_combinatorial/mux_tb_behav.wcfg -log simulate.log

